menu:
- {name: 'blog', url: '/blog'}
- {name: 'projects', url: '/projects'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/jihochoiii'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jihochoiii'}
