menu:
- {name: 'blog', url: '/blog'}
- {name: 'projects', url: '/projects'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'email', link: 'mailto:jihochoi@yonsei.ac.kr'}
- {icon: 'github', link: 'https://github.com/jihochoiii'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jihochoiii'}

contacts:
- {name: 'Jiho Choi', title: 'Senior Undergraduate Student', department: 'Electrical and Electronic Engineering', institution: 'Yonsei University', institution_address: '50 Yonsei-ro, Seodaemun-gu, Seoul', email: 'jihochoi@yonsei.ac.kr', image: 'assets/img/contact.jpg'}
